### PR TITLE
Upgrade pulumi-terraform-bridge to v3.61.0

### PR DESCRIPTION
**Pull request by t0yv0**
This PR was generated via `$ upgrade-provider pulumi/pulumi-azuread --kind bridge`.

---

- Upgrading pulumi-terraform-bridge from v3.60.1 to v3.61.0.

### CODE REVIEW

**Comment by t0yv0** [comment]
I'm confused why upgrade-provider generates PRs with a provider/go.sum conflict.

**Comment by iwahbe** [comment]
I'm guessing because you haven't pulled latest locally or https://github.com/pulumi/upgrade-provider/issues/160.

**Comment by t0yv0** [comment]
Now I get:

```
 ! [rejected]        upgrade-pulumi-terraform-bridge-to-v3.61.0 -> upgrade-pulumi-terraform-bridge-to-v3.61.0 (non-fast-forward)
error: failed to push some refs to 'github.com:pulumi/pulumi-azuread.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

[1] t0yv0@Antons-MacBook-Pro>                                                                                                                                                                         ~/code/pulumi-azuread
[1] t0yv0@Antons-MacBook-Pro> ~/code/upgrade-provider/upgrade-provider pulumi/pulumi-azuread --kind bridge                                                                                            ~/code/pulumi-azuread
```

This is highly unintuitive that uppgrade-provider messes with remote branches or PRs instead of starting from scratch.

**Comment by t0yv0** [comment]
Let me delete the branch locally and remotely and start over.

**Pull request closed without merging**
